// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vowwzppzzrbaxbycpyin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvd3d6cHB6enJiYXhieWNweWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTQxNTQsImV4cCI6MjA2ODY3MDE1NH0.AKrxN8aI4LHCcl9vu7WQKuXyo5wvDV0q2wwTFJV2Stg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});